# Generated by Django 5.0.6 on 2024-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
