# Generated by Django 5.0.6 on 2024-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_orders_address_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paymentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
